#!/bin/bash
SEED=413

# dataset parameters
MAX_SEQ_LENGTH=1024
VIRTUAL_PIECE_STEP_RATIO=1
FLATTEN_VIRTUAL_PIECES=true
PERMUTE_MPS=false
PERMUTE_TRACK_NUMBER=true
PITCH_AUGMENTATION_RANGE=0

# model parameter
USE_LINEAR_ATTENTION=false
LAYERS_NUMBER=12
ATTN_HEADS_NUMBER=12
EMBEDDING_DIM=768
NOT_USE_MPS_NUMBER=false

# training parameter
BATCH_SIZE=64
MAX_UPDATES=200000
MAX_EPOCHS=1
VALIDATION_INTERVAL=500

MAX_GRAD_NORM=1.0
LEARNING_RATE_PEAK=0.0006
LEARNING_RATE_WARMUP_UPDATES=700
LEARNING_RATE_DECAY_END_UPDATES=200000
LEARNING_RATE_DECAY_END_RATIO=1.0
EARLY_STOP=10

# training device
USE_DEVICE="cuda"
USE_ACCELERATE=true
MAX_PIECE_PER_GPU=8
export CUDA_VISIBLE_DEVICES=0

# generation & evaluation setting
EVAL_CONFIG_NAME="default"
